### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by beeirl** [kheruc/rt-next-motion#5]
Hi @kheruc,
your example inspired me to actually use Framer to add page transition to my Next.js application.
So far, everything works well as expected, except for dynamic routes. I have strictly followed the [Next.js documentation](https://nextjs.org/docs/routing/dynamic-routes) when creating the dynamic routes. But it looks like the prop `exitBeforeEnter` of Framer's `AnimatePresence` does not work. Do you have an idea what could be the reason for this?

**Comment by Druux** [comment]
``
